### ISSUE TITLE
There was an error getting Engine

### ISSUE THREAD

**Issue by zhanghongyong123456** [batselem/TensorRT-Openpose#2]
My configuration
win10 cuda10.1  cudnn 7.6.5   tensorRT 6.0.1.5  pytorch 1.8.1-cu101  python3.7   VS2019
I wonder if specific CUDA 11.1 and TensorRT are required to build the Engine
![10](https://user-images.githubusercontent.com/48466610/126257554-3e5bb427-e883-4c00-b8ec-d84de6e046e5.png)

**Comment by batselem** [comment]
It depends on GPU architecture. You need to install Tensorrt based on your version of gpu (sm) and cuda version. The code was tested on TensorRT 7.2.1.6 with CUDA 11.1 (Cudnn 8).

**Comment by zhanghongyong123456** [comment]
> It depends on GPU architecture. You need to install Tensorrt and cuda version based on your version of gpu (sm). The code was tested on TensorRT 7.2.1.6 with CUDA 11.1 (Cudnn 8). Also, please make sure that the path to the onnx file is correct.

I installed new Cuda11.1 and TensorRT7.2.1.6 and the engine works，I'm configuring human_pose_detection. sln, I'm configuring this and I can't find these *.lib  
![11](https://user-images.githubusercontent.com/48466610/126279358-70e4b117-8e11-4b17-abd4-27ad0faf0f57.png)
The released version of OpenCV that I downloaded or compiled myself did not have these lib
![12](https://user-images.githubusercontent.com/48466610/126279720-e59defc2-7363-401c-a11a-2dd70d63b41d.png)

**Comment by batselem** [comment]
Sorry I didn't include it in README. You need opencv library for CUDA 11.1, Cudnn 8. 
I built opencv 4.5.1 for cuda 11.1 using cmake. I will include the instruction for it later. YOu can follow https://haroonshakeel.medium.com/build-opencv-4-4-0-with-cuda-gpu-support-on-windows-10-without-tears-aa85d470bcd0 to install opencv. Both opencv 4.5.1 and 4.5.0 versions work.

**Comment by batselem** [comment]
you only need to have opencv_world451.lib. I checked it in my source, no idea where other ones came from. 

Set the following in your Linker->input
```
opencv_world450.lib
E:\Programs\TensorRT-7.2.1.6\lib\nvinfer.lib
E:\Programs\TensorRT-7.2.1.6\lib\nvinfer_plugin.lib
E:\Programs\TensorRT-7.2.1.6\lib\nvonnxparser.lib
E:\Programs\TensorRT-7.2.1.6\lib\nvparsers.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\lib\x64\cublas.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\lib\x64\cuda.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\lib\x64\cudart.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\lib\x64\cudnn.lib
```

**Comment by batselem** [comment]
It may work with the released version but I didn't test it with the released version. You can keep opencv_world451.lib and remove the other ones from the list.

**Comment by zhanghongyong123456** [comment]
> It may work with the released version but I didn't test it with the released version. You can keep opencv_world451.lib and remove the other ones from the list.



> Sorry I didn't include it in README. You need opencv library for CUDA 11.1, Cudnn 8.
> I built opencv 4.5.1 for cuda 11.1 using cmake GUI. I will include the instruction for it later. YOu can follow https://haroonshakeel.medium.com/build-opencv-4-4-0-with-cuda-gpu-support-on-windows-10-without-tears-aa85d470bcd0 to install opencv. Both opencv 4.5.1 and 4.5.0 versions work. Please make sure that all options with CUDA get checked.

OK, thank you very much for your reply. I've built OpenCV of Cuda10.1, but I installed Cuda11.1 to follow the test version you gave me, so I'm not sure if OpenCV is running. I'll compile OpenCV (Cuda11.1) again.I have two more questions to ask at CMAKE:
1. Do you need to check with_opengl
2. Do you need to check with_cuvid
3.   For OpenCV4.5.2 cuda10.1, which I have compiled successfully, I am always prompted with this error when I test with this link 
   https://github.com/opencv/opencv/blob/master/samples/gpu/video_reader.cpp，
![13](https://user-images.githubusercontent.com/48466610/126309775-982ecdfc-9896-4002-a92c-e73107561b09.png)，
I'm not sure what I'm going to do to run this example， https://github.com/opencv/opencv/blob/master/samples/gpu/video_reader.cpp

Looking forward to your reply

**Comment by zhanghongyong123456** [comment]
> It may work with the released version but I didn't test it with the released version. You can keep opencv_world451.lib and remove the other ones from the list.

I am not sure whether this is a bug or not. After I configured the environment, this appeared in the runtime. I did not specify this path, and my computer did not have this path either，I don't know if it was caused by my operation error，You can check to see if an absolute path is written
![14](https://user-images.githubusercontent.com/48466610/126312470-9acda6be-d99a-4e5b-a8a0-9d0dcf70cdec.png)

**Comment by zhanghongyong123456** [comment]
> 抱歉，我没有将它包含在 README 中。您需要用于 CUDA 11.1、Cudnn 8 的 opencv 库。
> 我使用 cmake GUI 为 cuda 11.1 构建了 opencv 4.5.1。稍后我将包括它的说明。您可以按照https://haroonshakeel.medium.com/build-opencv-4-4-0-with-cuda-gpu-support-on-windows-10-without-tears-aa85d470bcd0安装 opencv。opencv 4.5.1 和 4.5.0 版本都可以工作。请确保选中所有带有 CUDA 的选项。

**Comment by batselem** [comment]
Infer.h and NvInferRuntimeCommon.h are libraries of tensorrt. Vs is not finding these libraries. You may check your configration. You can follow the following tutorial to install it on windows:
<img width="1154" alt="Screen Shot 2021-07-20 at 9 36 54 PM" src="https://user-images.githubusercontent.com/6389915/126325200-905f82a9-6485-48d0-8708-7741aabfd4d7.png">
https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html

**Comment by zhanghongyong123456** [comment]
My computer is currently configured with cuda11.1, and I get the following results when I run human_pose_detection.sln using OpenCV (compiled with cuda10.1)，Is this correct when I run with CUDA10.1-compiled OpenCV，No attitude estimate is obtained
![16](https://user-images.githubusercontent.com/48466610/126324908-6268277f-ca27-4889-b091-d2f8326617c8.png)
![15](https://user-images.githubusercontent.com/48466610/126324928-ca3df04c-627e-4185-80e9-4dec18b4e133.png)

**Comment by batselem** [comment]
I can see that Tensorrt model is loaded successfully but there is a cuda execution error. What gpu are you using?

**Comment by batselem** [comment]
please make sure you install cuda as mentioned here [tensorrt-install-guide](https://github.com/batselem/TensorRT-Openpose/issues/2#issuecomment-883358984)

**Comment by zhanghongyong123456** [comment]
> I can see that Tensorrt model is loaded successfully but there is a cuda execution error. What gpu are you using?

My PC is using RTX 2060 supper, cuda11.1 cudnn 8.04 tensorRT7.2.1.6，python 3.7  pytorch 1.8.1 opencv 4.5.2（cuda10.1 compiled），because OpenCV 4.5.1 for cuda11.1 has not yet been compiled

**Comment by zhanghongyong123456** [comment]
> please make sure you install tensorrt as mentioned here [tensorrt-install-guide](https://github.com/batselem/TensorRT-Openpose/issues/2#issuecomment-883358984)

Thank you very much for your reply. I will wait for the compilation to finish（opencv4.5.1  cuda11.1） and run again

**Comment by batselem** [comment]
no problem. I found that CUDA version 10.0, 10.1, or 10.2 is only compatible with RTX 2060 super (check attachment). 
Why not try TensorRT 7.2.1 for Windows10 and CUDA 10.2 ZIP

<img width="623" alt="Screen Shot 2021-07-20 at 10 10 14 PM" src="https://user-images.githubusercontent.com/6389915/126329822-0674dbe0-3b58-44f1-b928-3a0abdf94b27.png">

**Comment by zhanghongyong123456** [comment]
> no problem. I found that CUDA version 10.0, 10.1, or 10.2 is only compatible with RTX 2060 super (check attachment).
> Why not try TensorRT 7.2.1 for Windows10 and CUDA 10.2 ZIP
> 
> <img alt="Screen Shot 2021-07-20 at 10 10 14 PM" width="623" src="https://user-images.githubusercontent.com/6389915/126329822-0674dbe0-3b58-44f1-b928-3a0abdf94b27.png">

I've reinstalled the version you tested, Cuda11.1, which I originally installed but failed to get the engine，If CUDA 11.1 doesn't work, I'll take your advice to try CUDA 10.2

**Comment by batselem** [comment]
Make sure your Tensorrt version is 7.2.1.*. I am afraid Tensorrt 6 won't work for this case.
![image](https://user-images.githubusercontent.com/6389915/126412364-80fc1af7-486f-40aa-b9f4-aa4b6ce91cb1.png)

**Comment by zhanghongyong123456** [comment]
> Make sure your Tensorrt version is 7. I recommend you to install 7.2.1.* specifically as shown in the figure. I am afraid that Tensorrt 6 won't work on this case.
> ![image](https://user-images.githubusercontent.com/6389915/126412364-80fc1af7-486f-40aa-b9f4-aa4b6ce91cb1.png)

Yes, I'm sure I installed 7.2.1.6 because yesterday I got an error on generating engine using cuda10.1 cudnn7.6.5 tensorRT 6.0.15, so I decided to install the version you tested.I still have this problem today with OpenCV4.5.1 compiled using Cuda11.1
:C:/source/rtSafe/cuda/reformat.cu (925) - Cuda Error in cuInt8::NCHWToNCHHW2: 209 (no kernel image is available for execution on the device)
FAILED_EXECUTION: Unknown exception

**Comment by zhanghongyong123456** [comment]
> Make sure your Tensorrt version is 7. I recommend you to install 7.2.1.* specifically as shown in the figure. I am afraid that Tensorrt 6 won't work on this case.
> ![image](https://user-images.githubusercontent.com/6389915/126412364-80fc1af7-486f-40aa-b9f4-aa4b6ce91cb1.png)

yes，There are some differences，I found that TensorRT6.0.1.5 does not have this file,
![17](https://user-images.githubusercontent.com/48466610/126419280-fa290fd9-5fce-47ba-90c1-90db5fa25159.png)

**Comment by batselem** [comment]
If you are using Tensor7 with cuda10.2, you also need opencv with cuda 10.2.

**Comment by zhanghongyong123456** [comment]
> If you are using Tensorrt7 with cuda10.2, you also need opencv with cuda 10.2. Sorry for inconvenience, but it also took me a few days to install all of these libraries.

I'm not sure what's causing this problem. Is it due to incompatibility between cuda11.1 and 2060 supper? I'm worried that there may be an initial problem when I install cuda10.2 and I can't get the engine，There was an error getting Engine #2，
 Open，If this method can be solved, I think it is no problem to try

**Comment by batselem** [comment]
win10 cuda10.1 cudnn 7.6.5 tensorRT 6.0.1.5. Here you are using TensorRT 6. I suggest you to use TensorRT 7 (7.2.1).

**Comment by batselem** [comment]
Suggested versions:
Cuda 10.2
TensorRT 7.2.1
Opencv with cuda 10.2

**Comment by zhanghongyong123456** [comment]
> Suggested versions:
> Cuda 10.2
> TensorRT 7.2.1
> Opencv with cuda 10.2

ok，Thank you very much for your advice. I will try it and hope it will be successful

**Comment by zhanghongyong123456** [comment]
> Suggested versions:
> Cuda 10.2
> TensorRT 7.2.1
> Opencv with cuda 10.2
I'm sorry to tell you, but it doesn't work. I don't know what to do，This is the result of my OpenCV Cuda10.2 build test
![18](https://user-images.githubusercontent.com/48466610/126463652-b2106f73-4b85-4ca7-b46c-dec5a305d02c.png)

C:/source/rtSafe/cuda/reformat.cu (925) - Cuda Error in cuInt8::NCHWToNCHHW2: 209 (no kernel image is available for execution on the device)
FAILED_EXECUTION: Unknown exception

**Comment by zhanghongyong123456** [comment]
> win10 cuda10.1 cudnn 7.6.5 tensorRT 6.0.1.5. Here you are using TensorRT 6. I suggest you to use TensorRT 7 (7.2.1).
when runing  E:\TensorRT-7.2.1.6-cu10.2\bin\trtexec.exe  --onnx=trt_pose.onnx --explicitBatch --saveEngine=trt_pose_fp16.engine --fp16
I wonder if this makes a difference
[07/21/2021-19:17:02] [I] [TRT] Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
![20](https://user-images.githubusercontent.com/48466610/126480917-89d257d4-1f53-4c96-a1c5-41c86d907f30.png)

**Comment by batselem** [comment]
It is not an error. just warning. It will take a few minutes to create an engine from onnx file.

**Comment by batselem** [comment]
![image](https://user-images.githubusercontent.com/6389915/126482401-0e3f50f8-a292-4c40-836d-8cf319602968.png)

**Comment by zhanghongyong123456** [comment]
> It is not an error. just warning. It will take a few minutes to create an engine from onnx file.

Yes, I would like to ask if he will affect the subsequent posture estimation, it does not appear to be the reason，
Yes, he is working normally, but what should I do about this problem，Cuda10.2 cuda11.1 both tried, still report an error
C:/source/rtSafe/cuda/reformat.cu (925) - Cuda Error in cuInt8::NCHWToNCHHW2: 209 (no kernel image is available for execution on the device)
FAILED_EXECUTION: Unknown exception

**Comment by zhanghongyong123456** [comment]
Hello, does this project need to separately configure and compile Openpose
https://github.com/CMU-Perceptual-Computing-Lab/openpose

**Comment by batselem** [comment]
No need to use CMU openpose for this project.

**Comment by zhanghongyong123456** [comment]
> No need to use CMU openpose for this project.
Do you think this has anything to do with it，Your GPU computing power is greater than mine
https://stackoverflow.com/questions/37325630/using-cuda-compiled-for-compute-capability-3-7-on-maxwell-gpus

**Comment by zhanghongyong123456** [comment]
> No need to use CMU openpose for this project.
I guess that's the problem
https://www.programmersought.com/article/92874479010/

**Comment by zhanghongyong123456** [comment]
> > It may work with the released version but I didn't test it with the released version. You can keep opencv_world451.lib and remove the other ones from the list.
> 
> I am not sure whether this is a bug or not. After I configured the environment, this appeared in the runtime. I did not specify this path, and my computer did not have this path either，I don't know if it was caused by my operation error，You can check to see if an absolute path is written
> ![14](https://user-images.githubusercontent.com/48466610/126312470-9acda6be-d99a-4e5b-a8a0-9d0dcf70cdec.png)

Sorry to bother you again, but I found that I do not have this path，C:/source/rtSafe/cuda/reformat.cu I don't know which path this is
![21](https://user-images.githubusercontent.com/48466610/126582239-cc933b8b-11ac-41df-bacf-67c7b86383bb.png)

**Comment by batselem** [comment]
https://forums.developer.nvidia.com/t/tensorrt-error-rtsafe-cuda-reformat-cu-925-cuda-error-in-nchwtonchhw2-400-invalid-resource-handle/157693/11

**Comment by zhanghongyong123456** [comment]
> https://forums.developer.nvidia.com/t/tensorrt-error-rtsafe-cuda-reformat-cu-925-cuda-error-in-nchwtonchhw2-400-invalid-resource-handle/157693/11

Yes, I also read this. It doesn't say how to solve it, does it

**Comment by zhanghongyong123456** [comment]
> https://forums.developer.nvidia.com/t/tensorrt-error-rtsafe-cuda-reformat-cu-925-cuda-error-in-nchwtonchhw2-400-invalid-resource-handle/157693/11
I think this is the problem. I want to know where to modify this. Your GPU is 86 while mine is 75, should I change 86 to 75
![23](https://user-images.githubusercontent.com/48466610/126595095-548050af-a8ee-4970-a76c-f7e9dff0b06c.png)

**Comment by batselem** [comment]
You can try to build tensorrt for your gpu arch 75 with cmake [TensorRT_github](https://github.com/NVIDIA/TensorRT) but I am afraid it is not supported on windows. I am not sure.

**Comment by batselem** [comment]
There is an option for setting SM arch as follows but I am not sure that you can build it on windows.
```
GPU_ARCHS: GPU (SM) architectures to target. By default we generate CUDA code for all major SMs. Specific SM versions can be specified here as a quoted space-separated list to reduce compilation time and binary size. Table of compute capabilities of NVIDIA GPUs can be found here. Examples:
NVidia A100: -DGPU_ARCHS="80"
Tesla T4, GeForce RTX 2080: -DGPU_ARCHS="75"
Titan V, Tesla V100: -DGPU_ARCHS="70"
Multiple SMs: -DGPU_ARCHS="80 75"
```

**Comment by zhanghongyong123456** [comment]
> You can try to build tensorrt for your gpu arch 75 with cmake [TensorRT_github](https://github.com/NVIDIA/TensorRT) but I am afraid it is not supported on windows. I am not sure.
I found the location you configured，trt_demo.vcxproj ，I'll change 86 to 75，It started to work
![24](https://user-images.githubusercontent.com/48466610/126595906-1d74fa0b-25f6-4fe6-a59a-9cf90cea27f7.png)

**Comment by batselem** [comment]
Hope it works ^^

**Comment by zhanghongyong123456** [comment]
> Hope it works ^^

I'm glad he got to work
![25](https://user-images.githubusercontent.com/48466610/126596408-d1ed80ef-e438-4077-8a8f-cd89c9dd266b.png)
1 . I would like to ask if I can get attitude information, such as coordinate points or JSON files, for pose estimation
2. Can multiple cameras get attitude information at the same time

**Comment by zhanghongyong123456** [comment]
> Hope it works ^^

Thank you very much for your continuous reply and answer. Thank you again

**Comment by batselem** [comment]
No problem. Good work!

**Comment by batselem** [comment]
Yes you can do it in threads to process multiple channels. For coordinate points you need to revise the trt_pose code .

**Comment by zhanghongyong123456** [comment]
> Yes you can do it in threads to process multiple channels. For coordinate points you need to revise the trt_pose code .



> Yes you can do it in threads to process multiple channels. For coordinate points you need to revise the trt_pose code .

ok，thanks for your reply，I would like to know how this project compares to the OpenPose project，Does it make a difference

**Comment by batselem** [comment]
The difference is that it runs on top of Tensorrt which makes it faster than CMU-OpenPose. With CMU-openpose you may be able to process 10 ~ 40frames per second depending your gpu.

**Comment by batselem** [comment]
As you experimented, with tensorrt, you can process frames almost 10times faster than the original openpose.

**Comment by zhanghongyong123456** [comment]
> As you experimented, with tensorrt, you can process frames almost 10times faster than the original openpose.

Ok, thanks for your answer

**Comment by batselem** [comment]
I will appreciate it if can star the project for my effort. Thanks

**Comment by zhanghongyong123456** [comment]
> I will appreciate it if can star the project for my effort. Thanks

It's such a good project, it's like a thumbs up

**Comment by batselem** [comment]
Thank you
